#!/bin/python3

import sys
def fibonacci_sum(n):
    a, b = 1, 2
    even_sum = 0

    while a <= n:
        if a % 2 == 0:
            even_sum += a
        a, b = b, a + b

    return even_sum
t = int(input().strip())
for a0 in range(t):
    n = int(input().strip())
    result = fibonacci_sum(n)
    print(result)
