#!/bin/python3

import sys


def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True


def nth_prime_number(n):
    primes = []
    num = 2
    while len(primes) < n:
        if is_prime(num):
            primes.append(num)
        num += 1
    return primes[-1]


t = int(input().strip())
for a0 in range(t):
    n = int(input().strip())
    result = nth_prime_number(n)
    print(result)
