#!/bin/python3

import sys


def sum_square_difference(n):
    # Calculate the sum of the squares
    sum_of_squares = sum(i**2 for i in range(1, n + 1))

    # Calculate the square of the sum
    square_of_sum = (sum(range(1, n + 1)))**2

    # Calculate the absolute difference
    difference = abs(square_of_sum - sum_of_squares)

    return difference


t = int(input().strip())
for a0 in range(t):
    n = int(input().strip())
    result = sum_square_difference(n)
    print(result)
